### ISSUE TITLE
Can't build framework on XCode 4.2 / OS X 10.7

### ISSUE THREAD

**Issue by tomtaylor** [mumble-voip/mumblekit#1]
Hello,

I'm having a bit of trouble building this as a framework on 10.7 with XCode 4.2. I'm slightly new to Mac Framework based development, so bear with me while I try and explain.

I've followed the instructions to build the framework inside my app, and it builds successfully (compiles ~700 files), but the framework in the tree structure is always red (missing) and I can't work out where the framework file is being placed on the disk.

A recent version of XCode added the Derived Data folders for build output, (Preferences -> Locations -> Derived Data) so I changed that to use "Location Specified by Targets", and now the files appear in a build folder in the project dir, but it fails when trying to copy the dylib files from the subprojects:

```
/Developer/usr/bin/clang++ -arch x86_64 -dynamiclib -isysroot /Developer/SDKs/MacOSX10.7.sdk -L/Users/tom/src/mumblekit/build/Debug -L/Users/tom/src/mumblekit -F/Users/tom/src/mumblekit/build/Debug -filelist "/Users/tom/src/mumblekit/build/MumbleKit.build/Debug/MumbleKit (Mac).build/Objects-normal/x86_64/MumbleKit.LinkFileList" -install_name "@loader_path/../Frameworks/MumbleKit.framework/Versions/A/MumbleKit" -mmacosx-version-min=10.7 -framework CoreAudio -framework AudioUnit -framework AudioToolbox -framework CoreServices -framework Cocoa -framework Foundation -framework Security /Users/tom/src/mumblekit/build/Debug/CELT-0.7.0.dylib /Users/tom/src/mumblekit/build/Debug/OpenSSL.dylib /Users/tom/src/mumblekit/build/Debug/ProtocolBuffers.dylib /Users/tom/src/mumblekit/build/Debug/Speex.dylib /Users/tom/src/mumblekit/build/Debug/SpeexDSP.dylib -single_module -compatibility_version 1 -current_version 1 -o /Users/tom/src/mumblekit/build/Debug/MumbleKit.framework/Versions/A/MumbleKit
clang: error: no such file or directory: '/Users/tom/src/mumblekit/build/Debug/CELT-0.7.0.dylib'
clang: error: no such file or directory: '/Users/tom/src/mumblekit/build/Debug/OpenSSL.dylib'
clang: error: no such file or directory: '/Users/tom/src/mumblekit/build/Debug/ProtocolBuffers.dylib'
clang: error: no such file or directory: '/Users/tom/src/mumblekit/build/Debug/Speex.dylib'
clang: error: no such file or directory: '/Users/tom/src/mumblekit/build/Debug/SpeexDSP.dylib'
```

At this point, I'm a bit beyond my XCode knowledge. Do you have any suggestions on how to build a framework successfully inside another project?

Thanks!

**Comment by fbartolom** [comment]
I managed to compile the whole in two different projects, once just importing the mumbleKit library and another time by copying it. All subtargets were appropriately produced. Yet, when I try to link the library with my 64 bits process, as requested by Apple, I get en error reporting all calls to the methods of the library as Undefined symbols for architecture x86_64: . Nothing of this happened in the first project, even if that could be by chance. I set the compilation to not just compile for the active architecture as suggested, but yet the 64 bit version of Mumble Kit seems not to be produced.
