### ISSUE TITLE
AST Deserialization Issue On CELT-0.7

### ISSUE THREAD

**Issue by KaiZhone** [mumble-voip/mumblekit#60]
Hi I'm having this error pop up whenever i'm trying to build the project, even after i created a blank project and cloning mumblekit and installing from scratch via read-me instruction.

error: input is not a PCH file: '/Users/kai/Library/Developer/Xcode/DerivedData/TestMumble-dujksylaedcqpwheqtkzmmavptvw/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/9107948004434689704/CELT-0.7.pch.gch'
fatal error: file '/Users/kai/Library/Developer/Xcode/DerivedData/TestMumble-dujksylaedcqpwheqtkzmmavptvw/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/9107948004434689704/CELT-0.7.pch.gch' is not a valid precompiled PCH file

I'm using Xcode 10.1 and swift 4, building a project for the iOS phone. If you need any more info let me know

**Comment by KaiZhone** [comment]
Okay, nvm found the solution, i went into CELT project's base.xcconfig file, set GCC_PRECOMPILE_PREFIX_HEADER from YES to NO and it fixed it.

**Comment by speby** [comment]
@KaiZhone Very nice.... that also fixed it for me, too.
